version: "3"
services:
  app:
    build: .
    image: meteor_strike_punch
    ports:
      - "3000:3000"
    volumes:
      - ".:/app"
      - "/app/node_modules"
    environment:
      - NODE_ENV=development
    env_file:
      - .env.local
networks:
  supabase_default:
    external: true